version: '1.0'
services:
  sql_library:
    image: postgres:latest
    container_name: library
    ports: 
      - 5455:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    volumes:
      - ./db/ddl/1_ddl.sql:/docker-entrypoint-initdb.d/1_ddl.sql
      - ./db/dml/2_dml.sql:/docker-entrypoint-initdb.d/2_dml.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always